
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[274] =
    {   0,
        0,    0,  103,  101,  100,   99,   99,   86,   98,   98,
       92,   85,  101,   80,   81,   90,   89,   77,   88,   84,
       91,   46,   46,   78,   74,   93,   79,   94,   97,   43,
       43,   82,   83,   95,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       75,   96,   76,   87,   73,    0,   51,    0,   59,   76,
       68,   60,    0,    0,   57,   65,   55,   66,   56,   67,
        0,   49,   42,    1,    2,   58,   50,   45,    0,   46,
        0,   46,   83,   75,   82,   64,   70,   72,   71,   63,
       43,    0,    0,   61,   43,   43,   43,   43,   43,   43,

       11,   43,   43,   43,   43,   43,   43,   43,   19,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   62,   69,   47,   52,    0,   49,   49,    0,
       50,   45,    0,   48,   44,   54,   53,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   17,
       43,   43,   20,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,    0,   49,    0,   49,    0,   50,   48,   44,
        4,   43,    6,    7,   43,   43,   43,   43,   43,   13,
       14,   43,   43,   43,   18,   43,   37,   21,   43,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   33,   43,   43,    0,   49,    5,    8,   43,
       43,   43,   43,   39,   43,   16,   43,   43,   43,   43,
       43,   24,   43,   43,   43,   43,   43,   43,   41,   31,
       43,   43,   35,   43,   43,   36,   12,   15,   43,   40,
        3,   43,   23,   25,   26,   27,   28,   29,   43,   43,
       43,   43,   10,   38,   43,   30,   43,   43,    9,   22,
       32,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    4,
        4,    4,    4,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[278] =
    {   0,
        0,    0,  402,  403,  403,  403,  403,  377,   60,  403,
       43,   60,  365,  403,  403,  375,   56,  403,   57,   55,
       65,   84,   77,  373,  403,   69,  373,   61,  403,    0,
       81,  403,  403,  372,  339,  341,   69,   37,   86,   51,
      342,   63,   25,  339,  349,   83,  330,  339,  337,  342,
      403,   74,  403,  403,  403,  112,  403,  383,  403,  403,
      403,  403,  100,  120,  403,  403,  403,  403,  403,  403,
      368,  129,  403,  403,  403,  403,  133,  163,  149,  142,
        0,  168,  403,  403,  403,  360,  403,  403,  403,  359,
        0,  115,  347,  403,  326,  338,  325,  340,  327,  333,

      319,  320,  317,  319,  316,  319,  316,  313,    0,   87,
      317,  316,  108,   67,  314,  123,  106,  318,  311,  160,
      156,  316,  403,  403,  403,  403,  193,  403,  198,  214,
      403,  189,  136,  219,  204,  403,  403,  310,  322,  317,
      305,  124,  151,  318,  314,  306,  303,  311,  314,    0,
      300,  302,    0,  307,  304,  303,  296,  299,  288,  290,
      292,  299,  285,  283,  283,  295,  294,  284,  288,  292,
      294,  283,  173,  234,  250,  403,  203,  252,  403,  242,
        0,  283,    0,    0,  274,  282,  271,  276,  277,    0,
        0,  271,  270,  267,    0,  265,    0,    0,  271,  264,

      264,  264,  261,  273,  259,  257,  262,  261,  256,  253,
      244,  249,    0,  237,  249,  212,  256,    0,    0,  239,
      240,  244,  242,    0,  230,    0,  238,  240,  225,  206,
      209,    0,  217,  214,  216,  200,  206,  207,    0,    0,
      197,  198,    0,  187,  187,    0,    0,    0,  183,    0,
        0,  173,    0,    0,    0,    0,    0,    0,  165,  161,
      138,  128,    0,    0,  113,    0,  110,   89,    0,    0,
        0,    0,  403,  304,  308,  310,  121
    } ;

static yyconst flex_int16_t yy_def[278] =
    {   0,
      273,    1,  273,  273,  273,  273,  273,  273,  274,  273,
      273,  273,  275,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  276,
      276,  273,  273,  273,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      273,  273,  273,  273,  273,  274,  273,  274,  273,  273,
      273,  273,  275,  275,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      277,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      276,  274,  275,  273,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  277,  273,  273,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  273,  273,  273,  273,  273,  273,  273,  273,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  273,  273,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,    0,  273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_nxt[469] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   30,   30,
       31,   30,   30,   32,    4,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   30,   42,   30,   43,   30,   30,
       30,   44,   45,   46,   47,   48,   49,   50,   30,   30,
       30,   51,   52,   53,   54,   57,   59,   60,   61,   66,
      111,   71,   68,   72,   72,  112,   84,   74,  100,   67,
       69,   70,   75,   62,   89,   90,   92,  101,   76,   85,
       93,   86,   87,   77,   58,   82,   82,  123,  106,   73,

       77,  107,   78,   78,   79,  109,   97,   80,   80,  125,
      158,   79,  110,   98,   80,   80,   81,   57,   79,   99,
       57,  159,  273,  135,   80,   79,  152,  115,  116,   63,
      272,   80,   80,  102,   64,  103,  124,  117,  104,   80,
      118,  153,   81,  163,  105,  156,   58,   72,   72,   58,
      271,  129,  129,  157,  134,  134,  127,  128,  164,  128,
      130,  131,  133,  131,  133,  270,  161,  134,  134,  269,
      127,  128,   80,   80,  130,  131,  128,  185,  186,   77,
      131,   78,   78,  162,   77,  268,   82,   82,  187,   80,
       79,  174,  174,  132,  132,   79,  188,   80,   80,   80,

      167,  170,  267,  171,   79,  168,  173,  266,  173,   79,
      132,  174,  174,  169,  265,   80,  129,  129,  132,  132,
      132,  178,  178,   80,  264,  175,  176,  177,  176,  177,
      217,  217,  178,  178,  180,  180,  132,  134,  134,  175,
      176,  263,  262,  261,  132,  176,  260,  179,  259,  179,
      258,  180,  174,  174,  257,  256,  255,  254,  253,  180,
      252,  179,  128,  216,  128,  216,  179,  251,  217,  217,
      178,  178,  180,  180,  217,  217,  128,  250,  249,  248,
      131,  128,  131,  247,  176,  246,  176,  245,  244,  180,
      243,  242,  241,  240,  131,  239,  238,  180,  176,  131,

      237,  236,  235,  176,   56,   56,   56,   56,   63,  234,
       63,   63,   91,   91,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  184,  183,  182,
      181,  172,  166,  165,  160,  155,  154,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,   64,  137,  136,  126,  273,  122,  121,  120,  119,
      114,  113,  108,   96,   95,   94,   88,   83,   65,   64,

       55,  273,    3,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273
    } ;

static yyconst flex_int16_t yy_chk[469] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,   11,   11,   12,   17,
       43,   20,   19,   20,   20,   43,   26,   21,   38,   17,
       19,   19,   21,   12,   28,   28,   31,   38,   21,   26,
       31,   26,   26,   23,    9,   23,   23,   52,   40,   20,

       22,   40,   22,   22,   23,   42,   37,   23,   23,   63,
      114,   22,   42,   37,   22,   22,   22,   56,   23,   37,
       92,  114,   64,  277,   23,   22,  110,   46,   46,   64,
      268,   22,   23,   39,   63,   39,   52,   46,   39,   22,
       46,  110,   22,  117,   39,  113,   56,   72,   72,   92,
      267,   77,   77,  113,  133,  133,   72,   72,  117,   72,
       77,   77,   79,   77,   79,  265,  116,   79,   79,  262,
       72,   72,   80,   80,   77,   77,   72,  142,  142,   78,
       77,   78,   78,  116,   82,  261,   82,   82,  143,   80,
       78,  173,  173,   78,   78,   82,  143,   80,   82,   82,

      120,  121,  260,  121,   78,  120,  127,  259,  127,   82,
       78,  127,  127,  120,  252,   82,  129,  129,   78,  132,
      132,  177,  177,   82,  249,  129,  129,  130,  129,  130,
      216,  216,  130,  130,  135,  135,  132,  134,  134,  129,
      129,  245,  244,  242,  132,  129,  241,  134,  238,  134,
      237,  135,  174,  174,  236,  235,  234,  233,  231,  135,
      230,  134,  174,  175,  174,  175,  134,  229,  175,  175,
      178,  178,  180,  180,  217,  217,  174,  228,  227,  225,
      178,  174,  178,  223,  217,  222,  217,  221,  220,  180,
      215,  214,  212,  211,  178,  210,  209,  180,  217,  178,

      208,  207,  206,  217,  274,  274,  274,  274,  275,  205,
      275,  275,  276,  276,  204,  203,  202,  201,  200,  199,
      196,  194,  193,  192,  189,  188,  187,  186,  185,  182,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  152,
      151,  149,  148,  147,  146,  145,  144,  141,  140,  139,
      138,  122,  119,  118,  115,  112,  111,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   93,   90,   86,   71,   58,   50,   49,   48,   47,
       45,   44,   41,   36,   35,   34,   27,   24,   16,   13,

        8,    3,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[103] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clang.lex"
/*
LEX FILE FOR A C LIKE LANGUAGE AS MENTIONED IN THE REF.PDF

FILE NAME: 				CLANG.LEX
FUNCTION: 				CONVERT THE GIVEN INPUT FILES-CODE INTO A SET OF TOKENS (DIRECTELY),
									TO BE PASSED ON TO THE PARSER TO GENRATE THE PARSE TREE.
SUBMITTED BY: 		GROUP 10, COMPILERS LAB, IIT PATNA
GROUP MEMBERS: 		TANMAY DAS (1401CS47)
									MAYANK GOYAL (1401CS25)
									AVANISH KUMAR DAS (1401CS05)
*/
/*
CONTRIBUTION BY:
	(1) TANMAY DAS:   			Creating the regex for required input types, constants, etc.;
													Creating the function to recognize comment of type / * * / and //;
													Creating the function for detection of printf() {specifically because the above
													mentioned declaration would not be included in the code as it implicit};
													Including the function count() to avoid/skip empty-space/tabs, etc along with
												  counting the column number at each line;
													Commenting the clang.lex file;

	(2) MAYANK GOYAL:				Mentioning all the operators required as per the c-like language and
													passing it to the output file.
													Including the yylineno variable at every newline detection to increment line number;
													Commenting the clang.lex file;

	(3) AVANISH KUMAR DAS:  Mentioning the restricted names of identifiers and passing it as token
	 												in the output file, lex.yy.c
													Commenting the clang.lex file;
*/
#line 41 "clang.lex"
	#include <stdio.h>
	#include "y.tab.h"
	extern YYSTYPE yylval;
	char yyprev[100];
	int open_brace = 1;
	int is_brace_start = 0;
	int func_par_define = 0;
	int no_of_local_var[1000] = {0};
	extern int yylineno;
	void count();
/*
	Defining all the restricted keywords.
	Defining all the constants/ numbers, etc and passing its value
	Defining all the operators used in the c-like language
*/
#line 720 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 61 "clang.lex"


#line 910 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 403 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "clang.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "clang.lex"
{comment2();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "clang.lex"
{comment1();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "clang.lex"
{ strcpy(yyprev,yytext); count(); return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(INT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(LONG); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(SHORT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(SIGNED); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(SIZEOF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(STATIC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(STRUCT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(SWITCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(TYPEDEF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(UNION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(UNSIGNED); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(VOID); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(VOLATILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(WHILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DEFINE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(LINE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(INCLUDE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(ERROR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(PRAGMA); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(UNDEF); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "clang.lex"
{strcpy(yyprev,yytext);count(); return(PRE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(check_type()); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 110 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 111 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 113 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(CONSTANT); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 119 "clang.lex"
{ strcpy(yyprev,yytext);count(); strcpy(yylval.val, yytext); return(STRING_LITERAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 123 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(ELLIPSIS); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 124 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 125 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 126 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(ADD_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 127 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(SUB_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 128 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(MUL_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 129 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DIV_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(MOD_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 131 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(AND_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 132 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(XOR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 133 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(OR_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(RIGHT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 135 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(LEFT_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(INC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 137 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(DEC_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 138 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(PTR_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(AND_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(OR_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(LE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(GE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(EQ_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(NE_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(';'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "clang.lex"
{ open_brace++; is_brace_start = 1; strcpy(yyprev,yytext);count(); return('{'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "clang.lex"
{ no_of_local_var[open_brace] = 0; open_brace--; is_brace_start = 0; strcpy(yyprev,yytext);count(); return('}'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(','); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 149 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(':'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 150 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('='); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 151 "clang.lex"
{ func_par_define = 1; strcpy(yyprev,yytext);count(); return('('); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 152 "clang.lex"
{ func_par_define = 0; strcpy(yyprev,yytext);count(); return(')'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 153 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('['); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 154 "clang.lex"
{ strcpy(yyprev,yytext);count(); return(']'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 155 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('.'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 156 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('&'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 157 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('!'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 158 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('~'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 159 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('-'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 160 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('+'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 161 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('*'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 162 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('/'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('%'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 164 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('<'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 165 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('>'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 166 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('^'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 167 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('|'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 168 "clang.lex"
{ strcpy(yyprev,yytext);count(); return('?'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 169 "clang.lex"
{ strcpy(yyprev,yytext);count(); return yytext[0]; }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 170 "clang.lex"
{ strcpy(yyprev,yytext);count();}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 171 "clang.lex"
{ strcpy(yyprev,yytext);count(); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 172 "clang.lex"
{ strcpy(yyprev,yytext);count(); return MACRO; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 174 "clang.lex"
ECHO;
	YY_BREAK
#line 1516 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 273);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 174 "clang.lex"



yywrap(){
	return(1);
}

/*
	Function to find multiline comment
*/

comment(){
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0);
		c += 1;

	if ((c1 = input()) != '/' && c != 0){
		unput(c1);
		goto loop;
	}

	if (c != 0)
		c1 += 1;
}

/*
	Function to find single line comment
*/

comment2(){
	char c, c1;
	while ((c = input()) != '\n' && c != 0);
		c += 1;
}

/*
	Function to find printf
*/
comment1(){
	char c, c1;

loop:
	while ((c = input()) != ')' && c != 0);
		c += 1;

	if ((c1 = input()) != ';' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0)
		c1 += 1;
}

/*
	Function to count the number of column
*/
int column = 0;
void count(){
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 4;
		else
			column++;
}

int check_type(){
	return(IDENTIFIER);
}

