#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from clang.yacc  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 31 "clang.yacc"

	#include <math.h>
	#include <stdlib.h>
	#include <stddef.h>
	#include <alloca.h>
	#include <string.h>
	#include <ctype.h>
	#include <stdio.h>
	#include <ctype.h>
	char *progname;
	int error_count = 0, func_count = 0;
	int var_define = 0;
	int add_check = 0;
	int function_check = 1;

	//func_name[] array is used to store all the function names.
	char func_name[1000][50];
	//line_error[] array is used to store all the errors in input file .
	char line_error[1000][200];
  // local_var[][] 2-d array is used for storing local variables in a given scope.
	char local_var[1000][100][100];		/* Contains all variables which are defined at
																		   particular line from top to bottom pasing of lines */
  //funcName is used to store function name globally.
	char funcName[1000];

	extern char yyprev[100];
	extern int is_brace_start;
	// open_brace is used to check the level of nesting in the current function
	extern int open_brace;
	//func_par_define is used to indicate parameters need to be stored at the next scope.
	extern int func_par_define;
	//no_of_local_var array is used to number of local variables at the given scope.
	extern int no_of_local_var[1000];	/* Contains number of local variables at particular line */
	//yyin is used to read the input file.
	extern FILE *yyin;
	//yylineno is used to store line number.
	extern int yylineno;

#line 71 "clang.yacc"
typedef union{
    char val[1000];
    int line_no;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENTIFIER	258
#define	CONSTANT	259
#define	STRING_LITERAL	260
#define	SIZEOF	261
#define	DEFINE	262
#define	LINE	263
#define	INCLUDE	264
#define	ERROR	265
#define	PRAGMA	266
#define	UNDEF	267
#define	PRE	268
#define	MACRO	269
#define	PTR_OP	270
#define	INC_OP	271
#define	DEC_OP	272
#define	LEFT_OP	273
#define	RIGHT_OP	274
#define	LE_OP	275
#define	GE_OP	276
#define	EQ_OP	277
#define	NE_OP	278
#define	AND_OP	279
#define	OR_OP	280
#define	MUL_ASSIGN	281
#define	DIV_ASSIGN	282
#define	MOD_ASSIGN	283
#define	ADD_ASSIGN	284
#define	SUB_ASSIGN	285
#define	LEFT_ASSIGN	286
#define	RIGHT_ASSIGN	287
#define	AND_ASSIGN	288
#define	XOR_ASSIGN	289
#define	OR_ASSIGN	290
#define	TYPE_NAME	291
#define	TYPEDEF	292
#define	EXTERN	293
#define	STATIC	294
#define	AUTO	295
#define	REGISTER	296
#define	CHAR	297
#define	SHORT	298
#define	INT	299
#define	LONG	300
#define	SIGNED	301
#define	UNSIGNED	302
#define	FLOAT	303
#define	DOUBLE	304
#define	CONST	305
#define	VOLATILE	306
#define	VOID	307
#define	STRUCT	308
#define	UNION	309
#define	ENUM	310
#define	ELLIPSIS	311
#define	CASE	312
#define	DEFAULT	313
#define	IF	314
#define	ELSE	315
#define	SWITCH	316
#define	WHILE	317
#define	DO	318
#define	FOR	319
#define	GOTO	320
#define	CONTINUE	321
#define	BREAK	322
#define	RETURN	323


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENTIFIER;
static const int CONSTANT;
static const int STRING_LITERAL;
static const int SIZEOF;
static const int DEFINE;
static const int LINE;
static const int INCLUDE;
static const int ERROR;
static const int PRAGMA;
static const int UNDEF;
static const int PRE;
static const int MACRO;
static const int PTR_OP;
static const int INC_OP;
static const int DEC_OP;
static const int LEFT_OP;
static const int RIGHT_OP;
static const int LE_OP;
static const int GE_OP;
static const int EQ_OP;
static const int NE_OP;
static const int AND_OP;
static const int OR_OP;
static const int MUL_ASSIGN;
static const int DIV_ASSIGN;
static const int MOD_ASSIGN;
static const int ADD_ASSIGN;
static const int SUB_ASSIGN;
static const int LEFT_ASSIGN;
static const int RIGHT_ASSIGN;
static const int AND_ASSIGN;
static const int XOR_ASSIGN;
static const int OR_ASSIGN;
static const int TYPE_NAME;
static const int TYPEDEF;
static const int EXTERN;
static const int STATIC;
static const int AUTO;
static const int REGISTER;
static const int CHAR;
static const int SHORT;
static const int INT;
static const int LONG;
static const int SIGNED;
static const int UNSIGNED;
static const int FLOAT;
static const int DOUBLE;
static const int CONST;
static const int VOLATILE;
static const int VOID;
static const int STRUCT;
static const int UNION;
static const int ENUM;
static const int ELLIPSIS;
static const int CASE;
static const int DEFAULT;
static const int IF;
static const int ELSE;
static const int SWITCH;
static const int WHILE;
static const int DO;
static const int FOR;
static const int GOTO;
static const int CONTINUE;
static const int BREAK;
static const int RETURN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENTIFIER=258
	,CONSTANT=259
	,STRING_LITERAL=260
	,SIZEOF=261
	,DEFINE=262
	,LINE=263
	,INCLUDE=264
	,ERROR=265
	,PRAGMA=266
	,UNDEF=267
	,PRE=268
	,MACRO=269
	,PTR_OP=270
	,INC_OP=271
	,DEC_OP=272
	,LEFT_OP=273
	,RIGHT_OP=274
	,LE_OP=275
	,GE_OP=276
	,EQ_OP=277
	,NE_OP=278
	,AND_OP=279
	,OR_OP=280
	,MUL_ASSIGN=281
	,DIV_ASSIGN=282
	,MOD_ASSIGN=283
	,ADD_ASSIGN=284
	,SUB_ASSIGN=285
	,LEFT_ASSIGN=286
	,RIGHT_ASSIGN=287
	,AND_ASSIGN=288
	,XOR_ASSIGN=289
	,OR_ASSIGN=290
	,TYPE_NAME=291
	,TYPEDEF=292
	,EXTERN=293
	,STATIC=294
	,AUTO=295
	,REGISTER=296
	,CHAR=297
	,SHORT=298
	,INT=299
	,LONG=300
	,SIGNED=301
	,UNSIGNED=302
	,FLOAT=303
	,DOUBLE=304
	,CONST=305
	,VOLATILE=306
	,VOID=307
	,STRUCT=308
	,UNION=309
	,ENUM=310
	,ELLIPSIS=311
	,CASE=312
	,DEFAULT=313
	,IF=314
	,ELSE=315
	,SWITCH=316
	,WHILE=317
	,DO=318
	,FOR=319
	,GOTO=320
	,CONTINUE=321
	,BREAK=322
	,RETURN=323


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENTIFIER=258;
const int YY_parse_CLASS::CONSTANT=259;
const int YY_parse_CLASS::STRING_LITERAL=260;
const int YY_parse_CLASS::SIZEOF=261;
const int YY_parse_CLASS::DEFINE=262;
const int YY_parse_CLASS::LINE=263;
const int YY_parse_CLASS::INCLUDE=264;
const int YY_parse_CLASS::ERROR=265;
const int YY_parse_CLASS::PRAGMA=266;
const int YY_parse_CLASS::UNDEF=267;
const int YY_parse_CLASS::PRE=268;
const int YY_parse_CLASS::MACRO=269;
const int YY_parse_CLASS::PTR_OP=270;
const int YY_parse_CLASS::INC_OP=271;
const int YY_parse_CLASS::DEC_OP=272;
const int YY_parse_CLASS::LEFT_OP=273;
const int YY_parse_CLASS::RIGHT_OP=274;
const int YY_parse_CLASS::LE_OP=275;
const int YY_parse_CLASS::GE_OP=276;
const int YY_parse_CLASS::EQ_OP=277;
const int YY_parse_CLASS::NE_OP=278;
const int YY_parse_CLASS::AND_OP=279;
const int YY_parse_CLASS::OR_OP=280;
const int YY_parse_CLASS::MUL_ASSIGN=281;
const int YY_parse_CLASS::DIV_ASSIGN=282;
const int YY_parse_CLASS::MOD_ASSIGN=283;
const int YY_parse_CLASS::ADD_ASSIGN=284;
const int YY_parse_CLASS::SUB_ASSIGN=285;
const int YY_parse_CLASS::LEFT_ASSIGN=286;
const int YY_parse_CLASS::RIGHT_ASSIGN=287;
const int YY_parse_CLASS::AND_ASSIGN=288;
const int YY_parse_CLASS::XOR_ASSIGN=289;
const int YY_parse_CLASS::OR_ASSIGN=290;
const int YY_parse_CLASS::TYPE_NAME=291;
const int YY_parse_CLASS::TYPEDEF=292;
const int YY_parse_CLASS::EXTERN=293;
const int YY_parse_CLASS::STATIC=294;
const int YY_parse_CLASS::AUTO=295;
const int YY_parse_CLASS::REGISTER=296;
const int YY_parse_CLASS::CHAR=297;
const int YY_parse_CLASS::SHORT=298;
const int YY_parse_CLASS::INT=299;
const int YY_parse_CLASS::LONG=300;
const int YY_parse_CLASS::SIGNED=301;
const int YY_parse_CLASS::UNSIGNED=302;
const int YY_parse_CLASS::FLOAT=303;
const int YY_parse_CLASS::DOUBLE=304;
const int YY_parse_CLASS::CONST=305;
const int YY_parse_CLASS::VOLATILE=306;
const int YY_parse_CLASS::VOID=307;
const int YY_parse_CLASS::STRUCT=308;
const int YY_parse_CLASS::UNION=309;
const int YY_parse_CLASS::ENUM=310;
const int YY_parse_CLASS::ELLIPSIS=311;
const int YY_parse_CLASS::CASE=312;
const int YY_parse_CLASS::DEFAULT=313;
const int YY_parse_CLASS::IF=314;
const int YY_parse_CLASS::ELSE=315;
const int YY_parse_CLASS::SWITCH=316;
const int YY_parse_CLASS::WHILE=317;
const int YY_parse_CLASS::DO=318;
const int YY_parse_CLASS::FOR=319;
const int YY_parse_CLASS::GOTO=320;
const int YY_parse_CLASS::CONTINUE=321;
const int YY_parse_CLASS::BREAK=322;
const int YY_parse_CLASS::RETURN=323;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		376
#define	YYFLAG		-32768
#define	YYNTBASE	95

#define YYTRANSLATE(x) ((unsigned)(x) <= 323 ? yytranslate[x] : 159)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    80,    94,    93,     2,    82,    75,     2,    69,
    70,    76,    77,    74,    78,    73,    81,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    88,    90,    83,
    89,    84,    87,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    71,     2,    72,    85,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    91,    86,    92,    79,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     6,    10,    12,    17,    21,    26,    30,
    34,    37,    40,    42,    46,    48,    51,    54,    57,    60,
    65,    67,    69,    71,    73,    75,    77,    79,    84,    86,
    90,    94,    98,   100,   104,   108,   110,   114,   118,   120,
   124,   128,   132,   136,   138,   142,   146,   148,   152,   154,
   158,   160,   164,   166,   170,   172,   176,   178,   184,   186,
   190,   192,   194,   196,   198,   200,   202,   204,   206,   208,
   210,   212,   214,   218,   220,   223,   227,   229,   232,   234,
   237,   239,   242,   244,   248,   250,   254,   256,   258,   260,
   262,   264,   266,   268,   270,   272,   274,   276,   278,   280,
   282,   284,   286,   288,   294,   299,   302,   304,   306,   308,
   311,   315,   318,   320,   323,   325,   327,   331,   333,   336,
   340,   345,   351,   354,   356,   360,   362,   366,   368,   370,
   373,   375,   377,   381,   386,   390,   395,   400,   404,   406,
   409,   412,   416,   418,   421,   423,   427,   429,   433,   436,
   439,   441,   443,   447,   449,   452,   454,   456,   459,   463,
   466,   470,   474,   479,   482,   486,   490,   495,   497,   501,
   506,   508,   512,   514,   516,   518,   520,   522,   524,   528,
   533,   537,   540,   544,   548,   553,   555,   558,   560,   563,
   565,   568,   570,   576,   584,   590,   596,   604,   611,   619,
   623,   626,   629,   632,   636,   638,   641,   643,   645,   647,
   652,   656,   660,   663,   670,   677,   681,   689,   692,   696,
   699,   703,   708
};

static const short yyrhs[] = {     3,
     0,     4,     0,     5,     0,    69,   114,    70,     0,    95,
     0,    96,    71,   114,    72,     0,    96,    69,    70,     0,
    96,    69,    97,    70,     0,    96,    73,     3,     0,    96,
    15,     3,     0,    96,    16,     0,    96,    17,     0,   112,
     0,    97,    74,   112,     0,    96,     0,    16,    98,     0,
    17,    98,     0,    99,   100,     0,     6,    98,     0,     6,
    69,   141,    70,     0,    75,     0,    76,     0,    77,     0,
    78,     0,    79,     0,    80,     0,    98,     0,    69,   141,
    70,   100,     0,   100,     0,   101,    76,   100,     0,   101,
    81,   100,     0,   101,    82,   100,     0,   101,     0,   102,
    77,   101,     0,   102,    78,   101,     0,   102,     0,   103,
    18,   102,     0,   103,    19,   102,     0,   103,     0,   104,
    83,   103,     0,   104,    84,   103,     0,   104,    20,   103,
     0,   104,    21,   103,     0,   104,     0,   105,    22,   104,
     0,   105,    23,   104,     0,   105,     0,   106,    75,   105,
     0,   106,     0,   107,    85,   106,     0,   107,     0,   108,
    86,   107,     0,   108,     0,   109,    24,   108,     0,   109,
     0,   110,    25,   109,     0,   110,     0,   110,    87,   114,
    88,   111,     0,   111,     0,    98,   113,   112,     0,    89,
     0,    26,     0,    27,     0,    28,     0,    29,     0,    30,
     0,    31,     0,    32,     0,    33,     0,    34,     0,    35,
     0,   112,     0,   114,    74,   112,     0,   111,     0,   117,
    90,     0,   117,   118,    90,     0,   120,     0,   120,   117,
     0,   121,     0,   121,   117,     0,   132,     0,   132,   117,
     0,   119,     0,   118,    74,   119,     0,   133,     0,   133,
    89,   144,     0,    37,     0,    38,     0,    39,     0,    40,
     0,    41,     0,    52,     0,    42,     0,    43,     0,    44,
     0,    45,     0,    48,     0,    49,     0,    46,     0,    47,
     0,   122,     0,   129,     0,    36,     0,   123,     3,    91,
   124,    92,     0,   123,    91,   124,    92,     0,   123,     3,
     0,    53,     0,    54,     0,   125,     0,   124,   125,     0,
   126,   127,    90,     0,   121,   126,     0,   121,     0,   132,
   126,     0,   132,     0,   128,     0,   127,    74,   128,     0,
   133,     0,    88,   115,     0,   133,    88,   115,     0,    55,
    91,   130,    92,     0,    55,     3,    91,   130,    92,     0,
    55,     3,     0,   131,     0,   130,    74,   131,     0,     3,
     0,     3,    89,   115,     0,    50,     0,    51,     0,   135,
   134,     0,   134,     0,     3,     0,    69,   133,    70,     0,
   134,    71,   115,    72,     0,   134,    71,    72,     0,   134,
    69,   137,    70,     0,   134,    69,   140,    70,     0,   134,
    69,    70,     0,    76,     0,    76,   136,     0,    76,   135,
     0,    76,   136,   135,     0,   132,     0,   136,   132,     0,
   138,     0,   138,    74,    56,     0,   139,     0,   138,    74,
   139,     0,   117,   133,     0,   117,   142,     0,   117,     0,
     3,     0,   140,    74,     3,     0,   126,     0,   126,   142,
     0,   135,     0,   143,     0,   135,   143,     0,    69,   142,
    70,     0,    71,    72,     0,    71,   115,    72,     0,   143,
    71,    72,     0,   143,    71,   115,    72,     0,    69,    70,
     0,    69,   137,    70,     0,   143,    69,    70,     0,   143,
    69,   137,    70,     0,   112,     0,    91,   145,    92,     0,
    91,   145,    74,    92,     0,   144,     0,   145,    74,   144,
     0,   147,     0,   151,     0,   148,     0,   152,     0,   153,
     0,   154,     0,     3,    88,   146,     0,    57,   115,    88,
   146,     0,    58,    88,   146,     0,    91,    92,     0,    91,
   150,    92,     0,    91,   149,    92,     0,    91,   149,   150,
    92,     0,   116,     0,   149,   116,     0,   146,     0,   150,
   146,     0,    90,     0,   114,    90,     0,     1,     0,    59,
    69,   114,    70,   146,     0,    59,    69,   114,    70,   146,
    60,   146,     0,    61,    69,   114,    70,   146,     0,    62,
    69,   114,    70,   146,     0,    63,   146,    62,    69,   114,
    70,    90,     0,    64,    69,   151,   151,    70,   146,     0,
    64,    69,   151,   151,   114,    70,   146,     0,    65,     3,
    90,     0,    66,    90,     0,    67,    90,     0,    68,    90,
     0,    68,   114,    90,     0,   156,     0,   155,   156,     0,
   157,     0,   116,     0,   158,     0,   117,   133,   149,   148,
     0,   117,   133,   148,     0,   133,   149,   148,     0,   133,
   148,     0,    93,     9,    94,     3,    13,    94,     0,    93,
     9,    83,     3,    13,    84,     0,    93,     8,     4,     0,
    93,     8,     4,    94,     3,    13,    94,     0,    93,    10,
     0,    93,    10,    14,     0,    93,    11,     0,    93,    11,
    14,     0,    93,     7,     3,     4,     0,    93,     7,     3,
    14,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   127,   137,   138,   139,   143,   144,   145,   146,   147,   148,
   149,   150,   154,   155,   159,   160,   161,   162,   163,   164,
   168,   169,   170,   171,   172,   173,   177,   178,   182,   183,
   184,   185,   189,   190,   191,   195,   196,   197,   201,   202,
   203,   204,   205,   209,   210,   211,   215,   216,   220,   221,
   224,   225,   229,   230,   234,   235,   240,   241,   245,   246,
   250,   251,   252,   253,   254,   255,   256,   257,   258,   259,
   260,   264,   265,   269,   273,   274,   278,   279,   280,   281,
   282,   283,   287,   288,   292,   293,   297,   298,   299,   300,
   301,   305,   306,   307,   308,   309,   310,   311,   312,   313,
   314,   315,   316,   320,   321,   322,   326,   327,   331,   332,
   336,   340,   341,   342,   343,   347,   348,   352,   353,   354,
   358,   359,   360,   364,   365,   369,   370,   374,   375,   379,
   380,   384,   394,   395,   396,   397,   398,   399,   403,   404,
   405,   406,   410,   411,   415,   416,   420,   421,   425,   426,
   427,   431,   432,   436,   437,   441,   442,   443,   447,   448,
   449,   450,   451,   452,   453,   454,   455,   459,   460,   461,
   465,   466,   470,   471,   472,   473,   474,   475,   479,   480,
   481,   485,   486,   487,   488,   492,   493,   497,   498,   502,
   503,   504,   510,   511,   512,   516,   517,   518,   519,   523,
   524,   525,   526,   527,   531,   532,   536,   537,   538,   542,
   543,   544,   545,   548,   549,   550,   551,   552,   553,   554,
   555,   556,   557
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENTIFIER",
"CONSTANT","STRING_LITERAL","SIZEOF","DEFINE","LINE","INCLUDE","ERROR","PRAGMA",
"UNDEF","PRE","MACRO","PTR_OP","INC_OP","DEC_OP","LEFT_OP","RIGHT_OP","LE_OP",
"GE_OP","EQ_OP","NE_OP","AND_OP","OR_OP","MUL_ASSIGN","DIV_ASSIGN","MOD_ASSIGN",
"ADD_ASSIGN","SUB_ASSIGN","LEFT_ASSIGN","RIGHT_ASSIGN","AND_ASSIGN","XOR_ASSIGN",
"OR_ASSIGN","TYPE_NAME","TYPEDEF","EXTERN","STATIC","AUTO","REGISTER","CHAR",
"SHORT","INT","LONG","SIGNED","UNSIGNED","FLOAT","DOUBLE","CONST","VOLATILE",
"VOID","STRUCT","UNION","ENUM","ELLIPSIS","CASE","DEFAULT","IF","ELSE","SWITCH",
"WHILE","DO","FOR","GOTO","CONTINUE","BREAK","RETURN","'('","')'","'['","']'",
"'.'","','","'&'","'*'","'+'","'-'","'~'","'!'","'/'","'%'","'<'","'>'","'^'",
"'|'","'?'","':'","'='","';'","'{'","'}'","'#'","'\"'","primary_expression",
"postfix_expression","argument_expression_list","unary_expression","unary_operator",
"cast_expression","multiplicative_expression","additive_expression","shift_expression",
"relational_expression","equality_expression","and_expression","exclusive_or_expression",
"inclusive_or_expression","logical_and_expression","logical_or_expression","conditional_expression",
"assignment_expression","assignment_operator","expression","constant_expression",
"declaration","declaration_specifiers","init_declarator_list","init_declarator",
"storage_class_specifier","type_specifier","struct_or_union_specifier","struct_or_union",
"struct_declaration_list","struct_declaration","specifier_qualifier_list","struct_declarator_list",
"struct_declarator","enum_specifier","enumerator_list","enumerator","type_qualifier",
"declarator","direct_declarator","pointer","type_qualifier_list","parameter_type_list",
"parameter_list","parameter_declaration","identifier_list","type_name","abstract_declarator",
"direct_abstract_declarator","initializer","initializer_list","statement","labeled_statement",
"compound_statement","declaration_list","statement_list","expression_statement",
"selection_statement","iteration_statement","jump_statement","translation_unit",
"external_declaration","function_definition","control_line",""
};
#endif

static const short yyr1[] = {     0,
    95,    95,    95,    95,    96,    96,    96,    96,    96,    96,
    96,    96,    97,    97,    98,    98,    98,    98,    98,    98,
    99,    99,    99,    99,    99,    99,   100,   100,   101,   101,
   101,   101,   102,   102,   102,   103,   103,   103,   104,   104,
   104,   104,   104,   105,   105,   105,   106,   106,   107,   107,
   108,   108,   109,   109,   110,   110,   111,   111,   112,   112,
   113,   113,   113,   113,   113,   113,   113,   113,   113,   113,
   113,   114,   114,   115,   116,   116,   117,   117,   117,   117,
   117,   117,   118,   118,   119,   119,   120,   120,   120,   120,
   120,   121,   121,   121,   121,   121,   121,   121,   121,   121,
   121,   121,   121,   122,   122,   122,   123,   123,   124,   124,
   125,   126,   126,   126,   126,   127,   127,   128,   128,   128,
   129,   129,   129,   130,   130,   131,   131,   132,   132,   133,
   133,   134,   134,   134,   134,   134,   134,   134,   135,   135,
   135,   135,   136,   136,   137,   137,   138,   138,   139,   139,
   139,   140,   140,   141,   141,   142,   142,   142,   143,   143,
   143,   143,   143,   143,   143,   143,   143,   144,   144,   144,
   145,   145,   146,   146,   146,   146,   146,   146,   147,   147,
   147,   148,   148,   148,   148,   149,   149,   150,   150,   151,
   151,   151,   152,   152,   152,   153,   153,   153,   153,   154,
   154,   154,   154,   154,   155,   155,   156,   156,   156,   157,
   157,   157,   157,   158,   158,   158,   158,   158,   158,   158,
   158,   158,   158
};

static const short yyr2[] = {     0,
     1,     1,     1,     3,     1,     4,     3,     4,     3,     3,
     2,     2,     1,     3,     1,     2,     2,     2,     2,     4,
     1,     1,     1,     1,     1,     1,     1,     4,     1,     3,
     3,     3,     1,     3,     3,     1,     3,     3,     1,     3,
     3,     3,     3,     1,     3,     3,     1,     3,     1,     3,
     1,     3,     1,     3,     1,     3,     1,     5,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     3,     1,     2,     3,     1,     2,     1,     2,
     1,     2,     1,     3,     1,     3,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     5,     4,     2,     1,     1,     1,     2,
     3,     2,     1,     2,     1,     1,     3,     1,     2,     3,
     4,     5,     2,     1,     3,     1,     3,     1,     1,     2,
     1,     1,     3,     4,     3,     4,     4,     3,     1,     2,
     2,     3,     1,     2,     1,     3,     1,     3,     2,     2,
     1,     1,     3,     1,     2,     1,     1,     2,     3,     2,
     3,     3,     4,     2,     3,     3,     4,     1,     3,     4,
     1,     3,     1,     1,     1,     1,     1,     1,     3,     4,
     3,     2,     3,     3,     4,     1,     2,     1,     2,     1,
     2,     1,     5,     7,     5,     5,     7,     6,     7,     3,
     2,     2,     2,     3,     1,     2,     1,     1,     1,     4,
     3,     3,     2,     6,     6,     3,     7,     2,     3,     2,
     3,     4,     4
};

static const short yydefact[] = {     0,
   132,   103,    87,    88,    89,    90,    91,    93,    94,    95,
    96,    99,   100,    97,    98,   128,   129,    92,   107,   108,
     0,     0,   139,     0,   208,     0,    77,    79,   101,     0,
   102,    81,     0,   131,     0,     0,   205,   207,   209,   123,
     0,     0,   143,   141,   140,     0,     0,     0,   218,   220,
    75,     0,    83,    85,    78,    80,   106,     0,    82,     0,
   186,     0,   213,     0,     0,     0,   130,   206,     0,   126,
     0,   124,   133,   144,   142,     0,   216,     0,     0,   219,
   221,     0,    76,     0,   211,     0,     0,   113,     0,   109,
     0,   115,   192,     1,     2,     3,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    21,    22,    23,    24,    25,    26,   190,   182,     5,
    15,    27,     0,    29,    33,    36,    39,    44,    47,    49,
    51,    53,    55,    57,    59,    72,     0,   188,   173,   175,
     0,     0,   174,   176,   177,   178,    85,   187,   212,   152,
   138,   151,     0,   145,   147,     0,     1,   135,    27,    74,
     0,     0,     0,     0,   121,   222,   223,     0,     0,     0,
    84,     0,   168,    86,   210,     0,   112,   105,   110,     0,
     0,   116,   118,   114,     0,     0,    19,     0,    16,    17,
     0,     0,     0,     0,     0,     0,     0,     0,   201,   202,
   203,     0,     0,   154,     0,     0,    11,    12,     0,     0,
     0,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    61,     0,    18,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   191,   184,     0,   183,   189,     0,
     0,   149,   156,   150,   157,   136,     0,   137,     0,   134,
   122,   127,   125,     0,     0,     0,   171,     0,   104,   119,
     0,   111,     0,   179,     0,     0,   181,     0,     0,     0,
     0,     0,   200,   204,     4,     0,   156,   155,     0,    10,
     7,     0,    13,     0,     9,    60,    30,    31,    32,    34,
    35,    37,    38,    42,    43,    40,    41,    45,    46,    48,
    50,    52,    54,    56,     0,    73,   185,   164,     0,     0,
   160,     0,   158,     0,     0,   146,   148,   153,     0,   215,
   214,     0,   169,   117,   120,    20,   180,     0,     0,     0,
     0,     0,    28,     8,     0,     6,     0,   165,   159,   161,
   166,     0,   162,     0,   217,   170,   172,   193,   195,   196,
     0,     0,     0,    14,    58,   167,   163,     0,     0,   198,
     0,   194,   197,   199,     0,     0
};

static const short yydefgoto[] = {   120,
   121,   292,   122,   123,   124,   125,   126,   127,   128,   129,
   130,   131,   132,   133,   134,   135,   136,   223,   137,   161,
    61,    62,    52,    53,    27,    28,    29,    30,    89,    90,
    91,   181,   182,    31,    71,    72,    32,    33,    34,    35,
    45,   319,   154,   155,   156,   205,   320,   255,   174,   268,
   138,   139,   140,    64,   142,   143,   144,   145,   146,    36,
    37,    38,    39
};

static const short yypact[] = {   680,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
     6,    15,    80,   263,-32768,    38,  1296,  1296,-32768,    10,
-32768,  1296,  1143,    -1,    52,   289,-32768,-32768,-32768,   -57,
    23,     4,-32768,-32768,    80,    51,   102,   -17,    95,   124,
-32768,   -28,-32768,  1123,-32768,-32768,   104,   484,-32768,   347,
-32768,    38,-32768,  1143,  1017,   299,    -1,-32768,    23,    70,
   -44,-32768,-32768,-32768,-32768,   122,   103,   203,   214,-32768,
-32768,    15,-32768,   690,-32768,  1143,   484,   484,  1046,-32768,
    20,   484,-32768,   131,-32768,-32768,   915,   952,   952,   969,
   140,   170,   180,   187,   623,   193,   260,   178,   189,   734,
   783,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   136,   420,   969,-32768,    82,   126,   215,    -4,   229,   205,
   179,   195,   259,    32,-32768,-32768,    43,-32768,-32768,-32768,
   427,   507,-32768,-32768,-32768,-32768,   196,-32768,-32768,-32768,
-32768,    68,   218,   210,-32768,    72,-32768,-32768,-32768,-32768,
   219,   -16,   969,    23,-32768,-32768,-32768,   290,   281,   282,
-32768,   690,-32768,-32768,-32768,  1066,-32768,-32768,-32768,   969,
    67,-32768,   222,-32768,   623,   783,-32768,   969,-32768,-32768,
   224,   623,   969,   969,   969,   244,   221,   217,-32768,-32768,
-32768,    71,   118,   125,   239,   310,-32768,-32768,   801,   969,
   311,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   969,-32768,   969,   969,   969,   969,   969,   969,
   969,   969,   969,   969,   969,   969,   969,   969,   969,   969,
   969,   969,   969,   969,-32768,-32768,   543,-32768,-32768,   964,
   837,-32768,    58,-32768,    78,-32768,  1275,-32768,   319,-32768,
-32768,-32768,-32768,   332,   262,   253,-32768,    -2,-32768,-32768,
    20,-32768,   969,-32768,   279,   623,-32768,   128,   142,   144,
   254,   221,-32768,-32768,-32768,  1199,    91,-32768,   969,-32768,
-32768,   161,-32768,    11,-32768,-32768,-32768,-32768,-32768,    82,
    82,   126,   126,   215,   215,   215,   215,    -4,    -4,   229,
   205,   179,   195,   259,   -43,-32768,-32768,-32768,   284,   285,
-32768,   287,    78,  1240,   869,-32768,-32768,-32768,   266,-32768,
-32768,   574,-32768,-32768,-32768,-32768,-32768,   623,   623,   623,
   969,   884,-32768,-32768,   969,-32768,   969,-32768,-32768,-32768,
-32768,   286,-32768,   294,-32768,-32768,-32768,   297,-32768,-32768,
   166,   623,   174,-32768,-32768,-32768,-32768,   623,   271,-32768,
   623,-32768,-32768,-32768,   362,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,   -60,-32768,  -102,    26,    28,    85,    40,   129,
   130,   132,   139,   165,-32768,   -65,   -24,-32768,  -100,   -58,
    14,     0,-32768,   288,-32768,   -36,-32768,-32768,   316,   -74,
   -68,-32768,   110,-32768,   304,   255,    24,   -18,   -30,   -20,
-32768,   -63,-32768,   160,-32768,   232,  -145,  -220,  -143,-32768,
   -93,-32768,   157,    27,   280,  -178,-32768,-32768,-32768,-32768,
   384,-32768,-32768
};


#define	YYLAST		1351


static const short yytable[] = {    26,
   160,   153,    44,    42,    67,   159,   254,    54,    40,   202,
   203,   196,    57,    25,   179,   232,   233,     1,   282,   177,
   224,    88,     1,   184,    75,    70,    55,    56,   267,   164,
   244,    59,   323,    69,   160,    26,   187,   189,   190,   159,
     1,   191,   204,   147,   347,    82,    43,   165,   249,    25,
    88,    88,    88,    76,     1,    88,   242,   164,   288,   173,
     1,    83,   159,   147,   152,    78,   323,    65,    74,    66,
     1,   332,   183,    73,    88,   261,    79,   148,   234,   235,
    86,    92,   346,    22,   244,   203,   141,   203,    22,   333,
    23,   274,   278,   279,   280,    23,    41,   160,   277,   148,
    58,   179,   159,   342,   262,    77,    22,   180,    80,   294,
    92,    92,    92,    23,   160,    92,   244,   204,   243,   159,
    22,   270,   297,   298,   299,   166,   250,    51,   251,    16,
    17,   253,   245,   252,    92,   167,   250,    81,   251,    88,
   271,   258,   315,    23,   244,   259,   324,   173,   325,    88,
   206,   207,   208,   249,   148,    23,   272,   225,   163,   286,
   284,   251,   226,   227,   159,   159,   159,   159,   159,   159,
   159,   159,   159,   159,   159,   159,   159,   159,   159,   159,
   159,   159,   337,   287,   293,   160,   343,   285,   357,    63,
   159,   244,   322,   286,    87,   251,   168,   338,   296,    92,
    23,   244,   228,   229,   209,   169,   210,   160,   211,    92,
    85,   339,   159,   340,   335,   244,   170,   244,   185,   316,
   149,    93,    67,   157,    95,    96,    97,   192,   159,   253,
   344,    42,   230,   231,   345,   369,    98,    99,   193,   244,
   361,   363,   175,   371,   358,   359,   360,   244,   194,   152,
   236,   237,   183,   300,   301,   195,   152,   302,   303,   160,
   352,   197,   198,   239,   159,   287,   354,   199,   370,    46,
    47,    48,    49,    50,   372,   308,   309,   374,   200,   238,
   240,   365,   241,   257,    84,   152,   159,   256,   375,   111,
   260,     1,   264,   265,   266,   112,   113,   114,   115,   116,
   117,   157,    95,    96,    97,   281,   283,   173,   289,   273,
   118,   276,   290,   295,    98,    99,   304,   305,   306,   307,
   364,   328,   341,   152,     2,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    13,    14,    15,    16,    17,
    18,    19,    20,    21,   329,   330,   331,    93,   336,    94,
    95,    96,    97,   348,   349,   366,   368,    22,   350,   355,
   373,   376,    98,    99,    23,   367,   310,   111,   311,   171,
   158,   312,   162,   112,   113,   114,   115,   116,   117,   313,
   334,    24,     2,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,   176,   100,   101,   102,   314,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   327,   275,   263,    68,
   247,   112,   113,   114,   115,   116,   117,    93,     0,    94,
    95,    96,    97,     0,     0,     0,   118,    60,   119,     0,
     0,     0,    98,    99,     0,   212,   213,   214,   215,   216,
   217,   218,   219,   220,   221,     0,     0,     0,     0,     0,
     0,     0,     2,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,     0,   100,   101,   102,     0,   103,   104,   105,
   106,   107,   108,   109,   110,   111,     0,     0,     0,     0,
     0,   112,   113,   114,   115,   116,   117,    93,   222,    94,
    95,    96,    97,     0,     0,     0,   118,    60,   246,     2,
     0,     0,    98,    99,     0,     8,     9,    10,    11,    12,
    13,    14,    15,    16,    17,    18,    19,    20,    21,     0,
     0,     0,     0,    93,     0,    94,    95,    96,    97,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    98,    99,
     0,     0,     0,   100,   101,   102,     0,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   157,    95,    96,    97,
     0,   112,   113,   114,   115,   116,   117,     0,     0,    98,
    99,     0,     0,     0,     0,     0,   118,    60,   248,   100,
   101,   102,     0,   103,   104,   105,   106,   107,   108,   109,
   110,   111,     0,     0,     0,     0,     0,   112,   113,   114,
   115,   116,   117,    93,     0,    94,    95,    96,    97,     0,
     0,     0,   118,    60,   317,     0,     0,     0,    98,    99,
     0,     0,   111,     0,     0,     0,     0,     0,   112,   113,
   114,   115,   116,   117,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   172,   356,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,   100,
   101,   102,     1,   103,   104,   105,   106,   107,   108,   109,
   110,   111,   157,    95,    96,    97,     0,   112,   113,   114,
   115,   116,   117,     0,     0,    98,    99,     0,     0,     0,
     0,     0,   118,    60,     0,     2,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,    20,    21,     0,   157,    95,    96,    97,
     0,     0,     0,     0,     0,     0,     0,     0,    22,    98,
    99,     0,     0,     0,     0,    23,     0,     0,   111,     0,
     0,     0,     0,     0,   112,   113,   114,   115,   116,   117,
     0,     0,    24,     0,     0,     0,     0,     0,     0,     0,
   172,     0,     0,     0,     0,   157,    95,    96,    97,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    98,    99,
     0,     0,   111,   157,    95,    96,    97,     0,   112,   113,
   114,   115,   116,   117,     0,     0,    98,    99,     2,     0,
     0,     0,     0,   201,     8,     9,    10,    11,    12,    13,
    14,    15,    16,    17,    18,    19,    20,    21,     0,   157,
    95,    96,    97,     0,     0,     0,     0,     0,     0,     0,
     0,   111,    98,    99,     0,     0,     0,   112,   113,   114,
   115,   116,   117,     0,     0,     0,     0,     0,     0,   111,
   291,   157,    95,    96,    97,   112,   113,   114,   115,   116,
   117,     0,     0,     0,    98,    99,   157,    95,    96,    97,
     0,     0,     0,     0,     0,     0,     0,     0,     0,    98,
    99,     0,     0,     0,     0,   111,     0,     0,   321,     0,
     0,   112,   113,   114,   115,   116,   117,   157,    95,    96,
    97,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    98,    99,     0,     0,     0,     0,     0,   111,     0,     0,
   353,     0,     0,   112,   113,   114,   115,   116,   117,     0,
     0,     0,   111,   362,   157,    95,    96,    97,   112,   113,
   114,   115,   116,   117,     0,     0,     1,    98,    99,     0,
     0,   157,    95,    96,    97,     0,     0,     0,     0,     0,
     0,     0,     0,   186,    98,    99,     0,     0,     0,   112,
   113,   114,   115,   116,   117,     0,     0,     0,     0,     2,
     3,     4,     5,     6,     7,     8,     9,    10,    11,    12,
    13,    14,    15,    16,    17,    18,    19,    20,    21,   150,
   188,     0,     0,     0,     0,     0,   112,   113,   114,   115,
   116,   117,   250,   318,   251,     0,     0,   111,     0,    23,
     0,     0,     0,   112,   113,   114,   115,   116,   117,     0,
     0,     0,     2,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    15,    16,    17,    18,    19,
    20,    21,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     2,     0,     0,     0,     0,   151,     8,     9,    10,
    11,    12,    13,    14,    15,    16,    17,    18,    19,    20,
    21,     2,     0,     0,     0,     0,     0,     8,     9,    10,
    11,    12,    13,    14,    15,    16,    17,    18,    19,    20,
    21,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   178,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   269,     2,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    15,    16,    17,    18,    19,    20,    21,     2,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    15,    16,    17,    18,    19,    20,    21,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    84,     0,    60,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    60,     2,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    13,    14,    15,    16,    17,
    18,    19,    20,    21,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   286,   318,   251,
     0,     0,     0,     0,    23,     2,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    19,    20,    21,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,   351,
     2,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,    15,    16,    17,    18,    19,    20,    21,
   326,     2,     3,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    13,    14,    15,    16,    17,    18,    19,    20,
    21
};

static const short yycheck[] = {     0,
    66,    65,    23,    22,    35,    66,   152,    26,     3,   110,
   111,   105,     3,     0,    89,    20,    21,     3,   197,    88,
   123,    58,     3,    92,    45,     3,    27,    28,   172,    74,
    74,    32,   253,    91,   100,    36,    97,    98,    99,   100,
     3,   100,   111,    62,    88,    74,    23,    92,   142,    36,
    87,    88,    89,     3,     3,    92,    25,    74,   204,    84,
     3,    90,   123,    82,    65,    83,   287,    69,    45,    71,
     3,    74,    91,    70,   111,    92,    94,    64,    83,    84,
    54,    58,    72,    69,    74,   186,    60,   188,    69,    92,
    76,   185,   193,   194,   195,    76,    91,   163,   192,    86,
    91,   176,   163,   282,   163,     4,    69,    88,    14,   210,
    87,    88,    89,    76,   180,    92,    74,   186,    87,   180,
    69,   180,   225,   226,   227,     4,    69,    90,    71,    50,
    51,   152,    90,   152,   111,    14,    69,    14,    71,   176,
    74,    70,   243,    76,    74,    74,    69,   172,    71,   186,
    15,    16,    17,   247,   141,    76,    90,    76,    89,    69,
    90,    71,    81,    82,   225,   226,   227,   228,   229,   230,
   231,   232,   233,   234,   235,   236,   237,   238,   239,   240,
   241,   242,   276,   204,   209,   251,   289,    70,   332,    33,
   251,    74,   251,    69,    91,    71,    94,    70,   223,   176,
    76,    74,    77,    78,    69,     3,    71,   273,    73,   186,
    54,    70,   273,    70,   273,    74,     3,    74,    88,   244,
    64,     1,   253,     3,     4,     5,     6,    88,   289,   250,
    70,   250,    18,    19,    74,    70,    16,    17,    69,    74,
   341,   342,    86,    70,   338,   339,   340,    74,    69,   250,
    22,    23,   271,   228,   229,    69,   257,   230,   231,   325,
   324,    69,     3,    85,   325,   286,   325,    90,   362,     7,
     8,     9,    10,    11,   368,   236,   237,   371,    90,    75,
    86,   347,    24,    74,    89,   286,   347,    70,     0,    69,
    72,     3,     3,    13,    13,    75,    76,    77,    78,    79,
    80,     3,     4,     5,     6,    62,    90,   332,    70,    88,
    90,    88,     3,     3,    16,    17,   232,   233,   234,   235,
   345,     3,    69,   324,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    48,    49,    50,    51,
    52,    53,    54,    55,    13,    84,    94,     1,    70,     3,
     4,     5,     6,    70,    70,    70,    60,    69,    72,    94,
    90,     0,    16,    17,    76,    72,   238,    69,   239,    82,
    72,   240,    69,    75,    76,    77,    78,    79,    80,   241,
   271,    93,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    87,    57,    58,    59,   242,    61,    62,    63,
    64,    65,    66,    67,    68,    69,   257,   186,   164,    36,
   141,    75,    76,    77,    78,    79,    80,     1,    -1,     3,
     4,     5,     6,    -1,    -1,    -1,    90,    91,    92,    -1,
    -1,    -1,    16,    17,    -1,    26,    27,    28,    29,    30,
    31,    32,    33,    34,    35,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    -1,    57,    58,    59,    -1,    61,    62,    63,
    64,    65,    66,    67,    68,    69,    -1,    -1,    -1,    -1,
    -1,    75,    76,    77,    78,    79,    80,     1,    89,     3,
     4,     5,     6,    -1,    -1,    -1,    90,    91,    92,    36,
    -1,    -1,    16,    17,    -1,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    -1,
    -1,    -1,    -1,     1,    -1,     3,     4,     5,     6,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    16,    17,
    -1,    -1,    -1,    57,    58,    59,    -1,    61,    62,    63,
    64,    65,    66,    67,    68,    69,     3,     4,     5,     6,
    -1,    75,    76,    77,    78,    79,    80,    -1,    -1,    16,
    17,    -1,    -1,    -1,    -1,    -1,    90,    91,    92,    57,
    58,    59,    -1,    61,    62,    63,    64,    65,    66,    67,
    68,    69,    -1,    -1,    -1,    -1,    -1,    75,    76,    77,
    78,    79,    80,     1,    -1,     3,     4,     5,     6,    -1,
    -1,    -1,    90,    91,    92,    -1,    -1,    -1,    16,    17,
    -1,    -1,    69,    -1,    -1,    -1,    -1,    -1,    75,    76,
    77,    78,    79,    80,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    91,    92,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    57,
    58,    59,     3,    61,    62,    63,    64,    65,    66,    67,
    68,    69,     3,     4,     5,     6,    -1,    75,    76,    77,
    78,    79,    80,    -1,    -1,    16,    17,    -1,    -1,    -1,
    -1,    -1,    90,    91,    -1,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,    54,    55,    -1,     3,     4,     5,     6,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    69,    16,
    17,    -1,    -1,    -1,    -1,    76,    -1,    -1,    69,    -1,
    -1,    -1,    -1,    -1,    75,    76,    77,    78,    79,    80,
    -1,    -1,    93,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    91,    -1,    -1,    -1,    -1,     3,     4,     5,     6,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    16,    17,
    -1,    -1,    69,     3,     4,     5,     6,    -1,    75,    76,
    77,    78,    79,    80,    -1,    -1,    16,    17,    36,    -1,
    -1,    -1,    -1,    90,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    55,    -1,     3,
     4,     5,     6,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    69,    16,    17,    -1,    -1,    -1,    75,    76,    77,
    78,    79,    80,    -1,    -1,    -1,    -1,    -1,    -1,    69,
    70,     3,     4,     5,     6,    75,    76,    77,    78,    79,
    80,    -1,    -1,    -1,    16,    17,     3,     4,     5,     6,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    16,
    17,    -1,    -1,    -1,    -1,    69,    -1,    -1,    72,    -1,
    -1,    75,    76,    77,    78,    79,    80,     3,     4,     5,
     6,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    16,    17,    -1,    -1,    -1,    -1,    -1,    69,    -1,    -1,
    72,    -1,    -1,    75,    76,    77,    78,    79,    80,    -1,
    -1,    -1,    69,    70,     3,     4,     5,     6,    75,    76,
    77,    78,    79,    80,    -1,    -1,     3,    16,    17,    -1,
    -1,     3,     4,     5,     6,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    69,    16,    17,    -1,    -1,    -1,    75,
    76,    77,    78,    79,    80,    -1,    -1,    -1,    -1,    36,
    37,    38,    39,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,     3,
    69,    -1,    -1,    -1,    -1,    -1,    75,    76,    77,    78,
    79,    80,    69,    70,    71,    -1,    -1,    69,    -1,    76,
    -1,    -1,    -1,    75,    76,    77,    78,    79,    80,    -1,
    -1,    -1,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    55,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    36,    -1,    -1,    -1,    -1,    70,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    36,    -1,    -1,    -1,    -1,    -1,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    92,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    92,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    55,    36,    37,
    38,    39,    40,    41,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    55,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    89,    -1,    91,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    91,    36,    37,    38,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    48,    49,    50,    51,
    52,    53,    54,    55,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    69,    70,    71,
    -1,    -1,    -1,    -1,    76,    36,    37,    38,    39,    40,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,    54,    55,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    70,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
    55
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 128 "clang.yacc"
{
	if(functionCheck(yyvsp[0].val)) {

	} else if(checkVariable(yyvsp[0].val)) {

	} else {
		addIdentifierError(yyvsp[0].val);
	}
;
    break;}
case 76:
#line 274 "clang.yacc"
{var_define = 0;;
    break;}
case 132:
#line 385 "clang.yacc"
{
	if(func_par_define) {
		strcpy(local_var[open_brace+1][no_of_local_var[open_brace+1]], yyvsp[0].val);
		no_of_local_var[open_brace+1]++;
	} else if(is_brace_start) {
		strcpy(local_var[open_brace][no_of_local_var[open_brace]], yyvsp[0].val);
		no_of_local_var[open_brace]++;
	}
;
    break;}
case 136:
#line 397 "clang.yacc"
{sprintf(funcName, "%s", yyvsp[-2]); addFunc();;
    break;}
case 138:
#line 399 "clang.yacc"
{sprintf(funcName, "%s", yyvsp[-1]); addFunc();;
    break;}
case 192:
#line 505 "clang.yacc"
{
;
    break;}
case 210:
#line 542 "clang.yacc"
{sprintf(funcName, "%s", yyvsp[-2].val); addFunc();;
    break;}
case 211:
#line 543 "clang.yacc"
{ sprintf(funcName, "%s", yyvsp[-1].val); addFunc();;
    break;}
case 212:
#line 544 "clang.yacc"
{ sprintf(funcName, "%s", yyvsp[-1].val); addFunc();;
    break;}
case 213:
#line 545 "clang.yacc"
{sprintf(funcName, "%s", yyvsp[0].val); addFunc();;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 560 "clang.yacc"


extern char yytext[];
extern int column;


main(int argc, char** argv){
	if (argc > 1){
		FILE *file;
		file = fopen(argv[1], "r");
		if (!file)
		{
			fprintf(stderr, "Could not open %s\n", argv[1]);
			exit(1);
		}
		yyin = file;
	}
	do {
		yyparse();
	} while (!feof(yyin));

		if(error_count > 0) {
			printf("FAIL\n");
			printErrors();
		}
		else {
			printf("PASS\n");
		}
}
/*
: used for priting parsing error.
*/
yyerror(){
	char abc[1000], abc1[1000];
	strcpy(abc, "Line Number: ");
	sprintf(abc1, "%d", yylineno);
	strcat(abc, abc1);
	strcat(abc, " '");
	strcat(abc, yyprev);
	strcat(abc, "' ");
	strcat(abc, "Unexpected Token");
	strcpy(line_error[error_count], abc);
	error_count++;
}
/*
used for adding functions in the symbol table.
*/
addFunc() {
	int i, len = strlen(funcName), a = 1;
	for(i = 0; i < func_count; i++) {
		if(!strcmp(func_name[i], funcName)) {
			a = 0;
			break;
		}
	}
	if(a) {
		char *str1 = malloc(sizeof(char)*len);
		for(i = 0; i < len && funcName[i] != '('; i++) {
			str1[i] = funcName[i];
		}
		strcpy(func_name[func_count], str1);
		free(str1);
		func_count++;
	}
	add_check = 0;
}

/*
used for checking function name is valid or not.
*/
int functionCheck(char str[]) {
	int i, a = 1;
	for(i = 0; i < func_count; i++) {
		if(!strcmp(func_name[i], str)) {
			a = 0;
			break;
		}
	}
	if(a) {
		return 0;
	}
	function_check = 1;
	return 1;
}

/*
used for cheking variable is defined or not
*/
int checkVariable(char str[]) {
	int i, j, a = 1;
	for(i = 1;i <= open_brace; i++) {
		for(j = 0; j <= no_of_local_var[i]; j++) {
			if(!strcmp(str, local_var[i][j])) {
				a = 0;
				break;
			}
		}
	}
	if(a) {
		return 0;
	}
	return 1;
}

/*
used for printing all the function names.
*/
printFuncNames() {
	int i;
	for(i = 0;i < func_count; i++) {
		// DO NOTHING
	}
}

/*
used for printing all the errors in thr input file.
*/
printErrors() {
	int i;
	printf("Total Errors : %d\n",error_count);
	for(i = 0; i < error_count; i++)
		printf("%s\n",line_error[i]);
}

addIdentifierError(char str[]) {
	char str1[1000] = "Line Number: ";
	char abc[10];
	sprintf(abc, "%d", yylineno);
	strcat(str1, abc);
	strcat(str1, " Identifier ");
	strcat(str1, str);
	strcat(str1, " not defined");
	strcpy(line_error[error_count], str1);
	error_count++;
}

addError(char c) {
	char abc[10];
	sprintf(abc, "%c", c);
	strcpy(line_error[error_count], abc);
	error_count++;
}
